In [1]:
import pandas as pd
import numpy as np

In [2]:
A = set(pd.read_csv("assets/rawdata_new.csv").columns.values.tolist())
B = set(pd.read_csv("assets/Atts_agroconcept_survey.csv", sep=';').columns.values.tolist())
C = set(pd.read_csv("assets/Atts_nonpart_survey.csv", sep=';').columns.values.tolist())

In [3]:
B - C

{'co22011', 'co22015', 'co22018', 'mainprodcution', 'reducpercent'}

In [4]:
C - B

set()

In [5]:
C

{'GHG_goal',
 'acknow_goal',
 'activ_arab',
 'activ_cattle',
 'activ_dairy',
 'activ_nonag',
 'activ_pig',
 'activ_poultry',
 'activ_special',
 'add',
 'add_agr_land',
 'add_eff',
 'add_imag',
 'age',
 'agroconcept',
 'animal_unit',
 'arable_land',
 'attain_acknow',
 'attain_biodiv',
 'attain_ghg',
 'attain_incom',
 'attain_soil',
 'attain_yield',
 'biodiv_goal',
 'biog',
 'biog_eff',
 'biog_imag',
 'breed',
 'breed_eff',
 'breed_imag',
 'cattle_animal_unit',
 'comp',
 'comp_eff',
 'comp_imag',
 'conc',
 'conc_eff',
 'conc_imag',
 'cons_farm',
 'cons_general',
 'cov',
 'cov_eff',
 'cov_imag',
 'covman',
 'covman_eff',
 'covman_imag',
 'dairy_cows',
 'drag',
 'drag_eff',
 'drag_imag',
 'eco_proof',
 'ecodr',
 'ecodr_eff',
 'ecodr_imag',
 'educ',
 'ego_id',
 'env_goal',
 'farmtype',
 'fruits',
 'grapes',
 'hor_shee_goa',
 'id_survey',
 'income_goal',
 'info_gew',
 'info_resul',
 'innov_early',
 'innov_others',
 'innov_pion',
 'innov_thorou',
 'innov_trad',
 'interviewtime',
 'lact',
 'lact_eff',
 'lact_imag',
 'legum',
 'legum_eff',
 'legum_imag',
 'ley',
 'lott_1',
 'lott_2',
 'lott_3',
 'net_name10_club',
 'net_name10_ext',
 'net_name10_fam',
 'net_name10_frien',
 'net_name10_imp',
 'net_name10_neigh',
 'net_name10_oth',
 'net_name10_part',
 'net_name10_vet',
 'net_name10_work',
 'net_name1_club',
 'net_name1_ext',
 'net_name1_fam',
 'net_name1_frien',
 'net_name1_imp',
 'net_name1_neigh',
 'net_name1_oth',
 'net_name1_part',
 'net_name1_vet',
 'net_name1_work',
 'net_name2_club',
 'net_name2_ext',
 'net_name2_fam',
 'net_name2_frien',
 'net_name2_imp',
 'net_name2_neigh',
 'net_name2_oth',
 'net_name2_part',
 'net_name2_vet',
 'net_name2_work',
 'net_name3_club',
 'net_name3_ext',
 'net_name3_fam',
 'net_name3_frien',
 'net_name3_imp',
 'net_name3_neigh',
 'net_name3_oth',
 'net_name3_part',
 'net_name3_vet',
 'net_name3_work',
 'net_name4_club',
 'net_name4_ext',
 'net_name4_fam',
 'net_name4_frien',
 'net_name4_imp',
 'net_name4_neigh',
 'net_name4_oth',
 'net_name4_part',
 'net_name4_vet',
 'net_name4_work',
 'net_name5_club',
 'net_name5_ext',
 'net_name5_fam',
 'net_name5_frien',
 'net_name5_imp',
 'net_name5_neigh',
 'net_name5_oth',
 'net_name5_part',
 'net_name5_vet',
 'net_name5_work',
 'net_name6_club',
 'net_name6_ext',
 'net_name6_fam',
 'net_name6_frien',
 'net_name6_imp',
 'net_name6_neigh',
 'net_name6_oth',
 'net_name6_part',
 'net_name6_vet',
 'net_name6_work',
 'net_name7_club',
 'net_name7_ext',
 'net_name7_fam',
 'net_name7_frien',
 'net_name7_imp',
 'net_name7_neigh',
 'net_name7_oth',
 'net_name7_part',
 'net_name7_vet',
 'net_name7_work',
 'net_name8_club',
 'net_name8_ext',
 'net_name8_fam',
 'net_name8_frien',
 'net_name8_imp',
 'net_name8_neigh',
 'net_name8_oth',
 'net_name8_part',
 'net_name8_vet',
 'net_name8_work',
 'net_name9_club',
 'net_name9_ext',
 'net_name9_fam',
 'net_name9_frien',
 'net_name9_imp',
 'net_name9_neigh',
 'net_name9_oth',
 'net_name9_part',
 'net_name9_vet',
 'net_name9_work',
 'network',
 'organic',
 'oth_land',
 'oth_spec_crops',
 'others_opinions',
 'percep_drought',
 'percep_frost',
 'percep_hail',
 'percep_heat',
 'percep_heavyrain',
 'percep_longrain',
 'perm_crops',
 'perm_grass',
 'pigs',
 'pigs_poultry',
 'plough',
 'plough_eff',
 'plough_imag',
 'poultry',
 'prot_cult',
 'qual_landscape',
 'region',
 'satisf_ldw',
 'satisf_total',
 'self_act',
 'self_cap',
 'self_conf',
 'self_not',
 'self_reduc',
 'share',
 'soc_compenv',
 'soc_compinc',
 'soc_env',
 'soc_impr',
 'soc_inc',
 'solar',
 'solar_eff',
 'solar_imag',
 'spec_crops',
 'suckler_cows',
 'thresh_ldw',
 'thresh_total',
 'total_agr_land',
 'trees',
 'vegetables',
 'workforce',
 'yield_goal'}

In [3]:
set(pd.read_csv("Atts_agroconcept_int.csv", sep=';')['ego_id'].tolist())-\
set(pd.read_csv("Atts_agroconcept_survey.csv", sep=';')['ego_id'].tolist())

set()

In [4]:
set(pd.read_csv("Atts_nonpart_int.csv", sep=';')['ego_id_nonpart'].tolist())-\
set(pd.read_csv("Atts_nonpart_survey.csv", sep=';')['ego_id'].tolist())

set()

In [5]:
set(pd.read_csv("Edges_agroconcept_and_external_contacts.csv", sep=';')['sender_id'].tolist())-\
set(pd.read_csv("Atts_agroconcept_int.csv", sep=';')['ego_id'].tolist())

set()

In [6]:
set(pd.read_csv("Edges_agroconcept_complete.csv", sep=';')['sender_id'].tolist())-\
set(pd.read_csv("Edges_agroconcept_complete.csv", sep=';')['receiver_id'].tolist())

{5, 23}

In [7]:
set(pd.read_csv("Edges_nonpart_all.csv", sep=';')['receiver_id'].tolist())-\
set(pd.read_csv("Atts_nonpart_int.csv", sep=';')['ego_id_nonpart'].tolist())

{nan,
 1.0,
 nan,
 nan,
 2.0,
 4.0,
 nan,
 5.0,
 6.0,
 7.0,
 9.0,
 10.0,
 nan,
 8.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 nan,
 nan,
 54.0,
 55.0,
 56.0,
 82.0,
 83.0,
 84.0,
 85.0,
 86.0,
 87.0,
 88.0,
 89.0,
 90.0,
 91.0,
 92.0,
 93.0,
 94.0,
 95.0,
 96.0,
 97.0,
 98.0,
 99.0,
 100.0,
 101.0,
 102.0,
 103.0,
 104.0,
 105.0,
 106.0,
 107.0,
 108.0,
 109.0,
 110.0,
 111.0,
 112.0,
 113.0,
 114.0,
 115.0,
 116.0,
 117.0,
 118.0,
 119.0}

In [8]:
pd.read_csv("Edges_agroconcept_and_external_contacts.csv", sep=';')

,sender_id,receiver_id,frequency,friend,workmate,neighbour,familymember,partner,colleague_association,other,...,workmate_bef,neighbour_bef,familymember_bef,partner_bef,colleague_association_bef,other_bef,influence_part,knowledge,advice_freq,trust
0,1,2,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1.0,4.0,0,4
1,1,29,2,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1.0,4.0,2,4
2,1,30,2,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1.0,5.0,2,4
3,1,20,2,0,1,0,0,0,1,0,...,0,0,0,0,0,1,1.0,3.0,2,4
4,1,26,1,0,1,0,0,0,1,0,...,0,0,0,0,0,0,1.0,4.0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,27,51,2,0,1,0,0,0,0,1,...,1,0,0,0,0,1,3.0,3.0,2,5
129,28,14,3,1,0,0,0,0,1,0,...,0,0,0,0,0,0,5.0,4.0,2,5
130,28,27,2,0,1,0,0,0,0,1,...,0,0,0,0,0,1,1.0,4.0,0,4
131,28,52,2,0,0,0,0,0,0,1,...,0,0,0,0,0,1,1.0,3.0,2,5
132,28,53,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1.0,3.0,2,5

In [9]:
pd.read_csv("Edges_nonpart_all.csv", sep=';')

,sender_id,receiver_id,nodetype,frequency,friend,workmate,neighbour,familymember,partner,colleague_association,other,knowledge,advice_freq,trust,contact_years
0,57,82.0,exchange,3.0,1,1,0,0,0,0,0,4.0,1.0,4.0,NaN
1,57,83.0,exchange,2.0,0,1,0,0,0,0,0,4.0,0.0,4.0,NaN
2,57,84.0,exchange,2.0,0,1,0,0,0,0,0,4.0,1.0,4.0,NaN
3,57,85.0,exchange,2.0,0,1,0,0,0,0,0,3.0,1.0,4.0,NaN
4,57,86.0,exchange,3.0,1,1,0,0,0,0,0,4.0,2.0,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,79,54.0,agroconcept_contact,0.0,0,1,0,0,0,0,0,NaN,NaN,NaN,20.0
200,79,14.0,agroconcept_contact,0.0,0,1,1,0,0,0,0,NaN,NaN,NaN,50.0
201,79,55.0,agroconcept_contact,0.0,0,1,0,0,0,0,0,NaN,NaN,NaN,10.0
202,79,10.0,agroconcept_contact,0.0,1,1,0,0,0,0,0,NaN,NaN,NaN,50.0
203,79,8.0,agroconcept_contact,0.0,0,1,0,0,0,0,0,NaN,NaN,NaN,15.0

In [10]:
pd.read_csv("Influence_agroconcept.csv", sep=';')

    sender_id  receiver_id  influence_x  influence_y
0           1          NaN     0.503289     0.501645
1           2         28.0     0.721491     0.697368
2           2          9.0     0.749269     0.399671
3           2         54.0     0.591374     0.852522
4           2         14.0     0.426535     0.676535
..        ...          ...          ...          ...
90         28         14.0     0.491594     0.448465
91         28         27.0     0.353436     0.527412
92         28          9.0     0.404971     0.667763
93         28         54.0     0.617690     0.621711
94         28         30.0     0.505117     0.561404

[95 rows x 4 columns]

In [11]:
pd.read_csv("Influence_nonagroconcept.csv", sep=';')

,sender_id,receiver_id,nodetype,influence_x,influence_y
0,57,124,influential people,0.264620,0.627193
1,57,125,influential people,0.500731,0.480263
2,57,84,influential people,0.422515,0.337171
3,57,126,influential people,0.598684,0.351974
4,57,127,influential people,0.461988,0.684759
5,58,14,influential people,0.297515,0.731908
6,58,104,influential people,0.488670,0.493969
7,60,104,influential people,0.304825,0.712171
8,60,NaN,influential people,0.667763,0.355811
9,60,60,influential people,0.448465,0.496711
10,61,14,influential people,0.493727,0.773596
11,62,128,influential people,0.415436,0.688397
12,62,129,influential people,0.591950,0.642344
13,63,125,influential people,0.477860,0.775986
14,65,29,influential people,0.332103,0.562724
15,66,14,influential people,0.502214,0.783154
16,68,Agrarpolitik CH,influential people,0.492251,0.505376
17,68,Zwischenhandel/Fenaco,influential people,0.548708,0.625448
18,68,Natur,influential people,0.494465,0.516726
19,71,19,influential people,0.489299,0.782557
20,71,12,influential people,0.599631,0.752688
21,72,21,influential people,0.548977,0.550000
22,72,9,influential people,0.395468,0.512353
23,72,54,influential people,0.341740,0.538824
24,72,14,influential people,0.485746,0.651176
25,72,27,influential people,0.638158,0.352941
26,72,1,influential people,0.630117,0.625882
27,72,108,influential people,0.408260,0.657059
28,73,14,influential people,0.507380,0.632616
29,74,130,influential people,0.514391,0.644564
30,74,125,influential people,0.434686,0.594982
31,76,14,influential people,0.322368,0.510965
32,76,120,influential people,0.617325,0.625548
33,76,Politik,influential people,0.513889,0.529605
34,76,Abnehmer,influential people,0.422515,0.406798
35,81,131,influential people,0.496345,0.503838
36,77,Fenaco,influential people,0.457237,0.478070
37,77,120,influential people,0.581140,0.759320
38,77,ZBV,influential people,0.520468,0.579496
39,78,128,influential people,0.414108,0.565241
40,78,132,influential people,0.592471,0.391447
41,78,133,influential people,0.511330,0.490680
42,79,Berater,influential people,0.338450,0.650768
43,79,Gemeinderat,influential people,0.502193,0.518640