In [1]:
import pandas as pd
import numpy as np

In [2]:
df_agcon_all = pd.read_csv("Edges_agroconcept_and_external_contacts.csv", sep=';')
df_nonpart_all = pd.read_csv("Edges_nonpart_all.csv", sep=';')

In [3]:
set(df_agcon_all.columns.values.tolist())-set(df_nonpart_all.columns.values.tolist())

{'colleague_association_bef',
 'familymember_bef',
 'frequency_bef',
 'friend_bef',
 'influence_part',
 'neighbour_bef',
 'other_bef',
 'partner_bef',
 'workmate_bef'}

In [4]:
df = pd.concat([df_agcon_all,df_nonpart_all])

In [7]:
df[df['sender_id']==1]

,sender_id,receiver_id,frequency,friend,workmate,neighbour,familymember,partner,colleague_association,other,...,familymember_bef,partner_bef,colleague_association_bef,other_bef,influence_part,knowledge,advice_freq,trust,nodetype,contact_years
0,1,2.0,1.0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,1.0,4.0,0.0,4.0,NaN,NaN
1,1,29.0,2.0,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,1.0,4.0,2.0,4.0,NaN,NaN
2,1,30.0,2.0,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,1.0,5.0,2.0,4.0,NaN,NaN
3,1,20.0,2.0,0,1,0,0,0,1,0,...,0.0,0.0,0.0,1.0,1.0,3.0,2.0,4.0,NaN,NaN
4,1,26.0,1.0,0,1,0,0,0,1,0,...,0.0,0.0,0.0,0.0,1.0,4.0,0.0,4.0,NaN,NaN
5,1,14.0,2.0,0,1,0,0,0,1,0,...,0.0,0.0,0.0,0.0,4.0,5.0,2.0,4.0,NaN,NaN
6,1,15.0,2.0,0,1,1,0,0,1,0,...,0.0,0.0,0.0,0.0,1.0,3.0,1.0,4.0,NaN,NaN

In [8]:
df[df['sender_id']==2]

,sender_id,receiver_id,frequency,friend,workmate,neighbour,familymember,partner,colleague_association,other,...,familymember_bef,partner_bef,colleague_association_bef,other_bef,influence_part,knowledge,advice_freq,trust,nodetype,contact_years
7,2,14.0,3.0,0,1,0,0,0,1,0,...,0.0,0.0,0.0,0.0,1.0,5.0,3.0,5.0,NaN,NaN
8,2,31.0,2.0,0,0,0,0,0,0,1,...,0.0,0.0,0.0,1.0,1.0,4.0,1.0,4.0,NaN,NaN
9,2,32.0,3.0,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,1.0,4.0,0.0,4.0,NaN,NaN

In [5]:
df.groupby(df['sender_id'])['frequency'].sum().to_dict()

{1: 12.0,
 2: 8.0,
 3: 8.0,
 4: 8.0,
 5: 13.0,
 6: 1.0,
 7: 11.0,
 8: 2.0,
 9: 23.0,
 10: 8.0,
 11: 1.0,
 12: 20.0,
 13: 6.0,
 14: 34.0,
 15: 15.0,
 16: 10.0,
 18: 18.0,
 19: 14.0,
 20: 17.0,
 21: 15.0,
 22: 13.0,
 23: 8.0,
 26: 21.0,
 27: 14.0,
 28: 8.0,
 57: 13.0,
 58: 10.0,
 59: 32.0,
 60: 18.0,
 61: 0.0,
 62: 9.0,
 63: 8.0,
 64: 7.0,
 65: 0.0,
 66: 6.0,
 67: 19.0,
 68: 8.0,
 69: 11.0,
 70: 0.0,
 71: 0.0,
 72: 21.0,
 73: 14.0,
 74: 0.0,
 75: 9.0,
 76: 25.0,
 77: 8.0,
 78: 17.0,
 79: 9.0,
 80: 2.0,
 81: 19.0}